id: P006761
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG14598
  title: མེང་ཐོན་གྱི་མྱོང་བའི་ཟིན་ཐོ་གཅེས་བསྡུས།
  author: ''
  volumes:
    eafb7f3def3a4966a591abc46e8f806b:
      image_group_id: I1KG26402
      title: ''
      volume_number: 1
      total_pages: 242
      base_file: v001.txt
